version: '3.8'

services:
  php:
    image: php:8.2-fpm
    container_name: symfony_php
    build: ./docker/php
    volumes:
      - .:/var/www/symfony/app
    environment:
      XDEBUG_CONFIG: "remote_host=10.10.12.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=litvinov.local"
    expose:
      - 9003
      - 9000
    networks:
      - symfony

  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/symfony/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - symfony

networks:
  symfony:
    driver: bridge